#! /bin/bash
if [ "${1}"  == "--help" ]; then
    echo "Options for running this configuration file:"
    echo "--help                    Prints this message"
    echo "--ReBuild                 Cleans out existing downloads and resets the configuration"
    echo "--useRoot <ROOTSYSPath>   Configures the enviroment to use root versions <ROOTSYSPath> instead of default version" 
    echo "--cherepanov              Configures the make file to compile files in the directory cherepanov"



else

    echo "Configuring Environment...."
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/CommonUtils/lib
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/DataFormats/lib
    export DATAFORMATS_LIB=$PWD/DataFormats/lib/libDataFormats.so
    export codedir=$PWD
    ## setup variables for make files
#    export ROOTSYS=/libcern/root/5.34.18/sl6.3-x86_64
#    source /libcern/gcc/4.9.3/sl6.5-x86_64/setup.sh
#    export ROOTSYS=/libcern/root/6.06.08/sl6.6-x86_64
#    ROOT="$PWD/../root/"
    if [ "${1}"  == "--useRoot" ]; then
        export ROOTSYS=${2}
        ROOT="$PWD/../root/"
    fi
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROOTSYS/lib/
    export PATH=$PATH:$ROOTSYS/bin/
    
    for var in $@ ; do
	if [ "${var}" == "--ReBuild" ]; then
#	    rm -rf CommonUtils/SimpleFits 
#	    rm -rf CommonUtils/TauDataFormat 
	    rm -rf CommonUtils/lib
	    rm make.inc
	fi
    done
    
    myINC=$(ls | grep make.inc | wc -l)
    if [ $myINC == 0 ]; then
	echo "# -*- mode: makefile-gmake -*-" >> make.inc
	for var in $@ ; do
		echo ${var}

	    if [ "${var}" == "--cherepanov" ]; then
		echo "Configuring Code to use directory cherepanov"
		echo "USE_cherepanov=1" >> make.inc
	    fi

	done
    fi
    
    ## now downloading required code from github
    cd CommonUtils
    CommonUtils=$(ls | grep TauDataFormat | wc -l)
    cd ..
    if [ $CommonUtils == 0 ]; then
	cd CommonUtils
	mkdir lib
	
	git clone https://github.com/cherepan/SimpleFits.git SimpleFits
	
	git clone https://github.com/cherepan/TauDataFormat.git TauDataFormat
	
	git clone https://github.com/TauPolSoftware/TauDecaysInterface.git TauPolSoftware/TauDecaysInterface

	cd ../
    fi

    
    echo "Environment Configured"
fi
