#! /bin/bash
if [ "${1}"  == "--help" ]; then
    echo "Options for running this configuration file:"
    echo "--help                    Prints this message"
    echo "--ReBuild                 Cleans out existing downloads and resets the configuration"
    echo "--useRoot <ROOTSYSPath>   Configures the enviroment to use root versions <ROOTSYSPath> instead of default version" 
    echo "--cherepanov              Configures the make file to compile files in the directory cherepanov"
    echo "--joshi                   Configures the make file to compile files in the directory joshi"



else

    echo "Configuring Environment...."
 #   export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/CommonUtils/lib
 #   export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/DataFormats/lib
 #   export DATAFORMATS_LIB=$PWD/DataFormats/lib/libDataFormats.so
    ## setup variables for make files
    export codedir=$PWD
    source /cvmfs/sft.cern.ch/lcg/external/gcc/4.9.1/x86_64-slc6-gcc48-opt/setup.sh
    export ROOTSYS=/cvmfs/sft.cern.ch/lcg/app/releases/ROOT/5.34.36/x86_64-slc6-gcc49-opt/root/
    source /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/5.34.36/x86_64-slc6-gcc49-opt/root/bin/thisroot.sh
 

    if [ "${1}"  == "--useRoot" ]; then
        export ROOTSYS=${2}
        ROOT="$PWD/../root/"
    fi
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROOTSYS/lib/
    export PATH=$PATH:$ROOTSYS/bin/
    
    for var in $@ ; do
	if [ "${var}" == "--ReBuild" ]; then
#	    rm -rf CommonUtils/SimpleFits 
#	    rm -rf CommonUtils/TauDataFormat 
#	    rm -rf CommonUtils/lib
	    rm make.inc
	fi
    done
    
    myINC=$(ls | grep make.inc | wc -l)
    if [ $myINC == 0 ]; then
	echo "# -*- mode: makefile-gmake -*-" >> make.inc
	for var in $@ ; do
		echo ${var}

	    if [ "${var}" == "--cherepanov" ]; then
		echo "Configuring Code to use directory cherepanov"
		echo "USE_cherepanov=1" >> make.inc
	    fi

	    if [ "${var}" == "--joshi" ]; then
		echo "Configuring Code to use directory joshi"
		echo "USE_joshi=1" >> make.inc
	    fi

	done
    fi
    
    ## now downloading required code from github
    cd CommonUtils
    CommonUtils=$(ls | grep TauDataFormat | wc -l)
    cd ..
    if [ $CommonUtils == 0 ]; then
	cd CommonUtils

	cd ../
    fi

    
    echo "Environment Configured"
fi
