#! /bin/bash
if [ "${1}"  == "--help" ]; then
    echo "Options for running this configuration file:"
    echo "--help                    Prints this message"
    echo "--ReBuild                 Cleans out existing downloads and resets the configuration"
    echo "--useRoot <ROOTSYSPath>   Configures the enviroment to use root versions <ROOTSYSPath> instead of default version" 
    echo "--cherepanov              Configures the make file to compile files in the directory cherepanov"
    echo "--joshi                   Configures the make file to compile files in the directory joshi"
    echo "--wang                    Configures the make file to compile files in the directory wang"
    echo "--menendez                Configures the make file to compile files in the directory menendez"
    echo "--madhu                   Configures the make file to compile files in the directory madhu"
else

    echo "Configuring Environment...."
    ## setup variables for make files
    cd CommonUtils
    CommonUtils=$(ls | grep CMSSW_9_3_8 | wc -l)
    cd ..
    if [ $CommonUtils == 0 ]; then
	cd CommonUtils
	export cmssw_version=CMSSW_9_3_8
	export VO_CMS_SW_DIR=/cvmfs/cms.cern.ch
	source $VO_CMS_SW_DIR/cmsset_default.sh
	export SCRAM_ARCH=${scram_arch_version}
	scramv1 project CMSSW ${cmssw_version}
	cd ${cmssw_version}/src
	eval `scramv1 runtime -sh`
	cd ../../
	cd ../
    fi

    if [ "${1}"  == "--useRoot" ]; then
        export ROOTSYS=${2}
        ROOT="$PWD/../root/"
    fi
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROOTSYS/lib/
    export PATH=$PATH:$ROOTSYS/bin/

    for var in $@ ; do
	if [ "${var}" == "--ReBuild" ]; then
	    rm -rf CommonUtils/lib
	    rm make.inc
	fi
    done
    
    myINC=$(ls | grep make.inc | wc -l)
    if [ $myINC == 0 ]; then
	echo "# -*- mode: makefile-gmake -*-" >> make.inc
	for var in $@ ; do
	    if [ "${var}" == "--cherepanov" ]; then
		echo "Configuring Code to use directory cherepanov"
		echo "USE_cherepanov=1" >> make.inc
	    fi

	    if [ "${var}" == "--joshi" ]; then
		echo "Configuring Code to use directory joshi"
		echo "USE_joshi=1" >> make.inc
	    fi


	    if [ "${var}" == "--wang" ]; then
		echo "Configuring Code to use directory wang"
		echo "USE_wang=1" >> make.inc
	    fi

	    if [ "${var}" == "--menendez" ]; then
		echo "Configuring Code to use directory menendez"
		echo "USE_menendez=1" >> make.inc
	    fi

	    if [ "${var}" == "--madhu" ]; then
		echo "Configuring Code to use directory madhu"
		echo "USE_madhu=1" >> make.inc
	    fi
	done
    fi
    echo "Environment Configured"
fi
